const { chromium } = await import(process.env.PLAYWRIGHT_MODULE || 'playwright');
import assert from 'node:assert/strict';
const browser = await chromium.launch({channel:'chrome',headless:true});
const page = await browser.newPage({viewport:{width:1440,height:1000}});
const errors=[]; page.on('pageerror',e=>errors.push(e.message));
await page.route('https://**/*',r=>r.abort());
await page.goto((process.env.CHAINPAY_PREVIEW_URL || 'http://127.0.0.1:5189/'));
await page.getByRole('heading',{level:1}).waitFor();
await page.waitForTimeout(1200);
await page.screenshot({path:'/tmp/chainpay-landing-desktop.png',fullPage:true});
assert.equal(await page.locator('.story-chapter').count(),4);
await page.getByRole('link',{name:'See a receipt'}).click();
await page.waitForTimeout(1100);
assert.ok(await page.locator('#receipts').evaluate(e=>Math.abs(e.getBoundingClientRect().top)<200));
await page.screenshot({path:'/tmp/chainpay-landing-receipt.png'});
await page.emulateMedia({reducedMotion:'reduce'});
await page.waitForFunction(()=>!document.documentElement.classList.contains('lenis'));
await page.setViewportSize({width:390,height:844});
await page.goto((process.env.CHAINPAY_PREVIEW_URL || 'http://127.0.0.1:5189/'));
await page.getByRole('heading',{level:1}).waitFor();
assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
await page.getByRole('button',{name:'Open menu',exact:true}).click();
await page.keyboard.press('Escape');
assert.equal(await page.getByRole('button',{name:'Open menu',exact:true}).getAttribute('aria-expanded'),'false');
await page.screenshot({path:'/tmp/chainpay-landing-mobile.png',fullPage:true});
await page.setViewportSize({width:320,height:700});
assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
const cta = await page.locator('.landing-cta button').evaluate(e=>({background:getComputedStyle(e).backgroundColor,color:getComputedStyle(e).color}));
assert.notEqual(cta.background, 'rgb(0, 82, 255)');
await page.getByRole('button',{name:'Open dashboard',exact:true}).first().click();
await page.waitForURL('**/app/overview');
assert.deepEqual(errors,[]);
console.log('PASS: desktop, receipt anchor, reduced motion cleanup, mobile overflow, menu Escape, dashboard route; no runtime errors.');
await browser.close();
